// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZMOFbboEWK2R7GMKJ4UMrSNg2Y-gB9Ws',
    appId: '1:675039619764:android:d944a6d19c68389e9845e1',
    messagingSenderId: '675039619764',
    projectId: 'riseupgraded',
    storageBucket: 'riseupgraded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLLFXNIg_qSzwGrmVaEq38bR0ZkAMCQ8M',
    appId: '1:675039619764:ios:ea798ee5fede6d419845e1',
    messagingSenderId: '675039619764',
    projectId: 'riseupgraded',
    storageBucket: 'riseupgraded.appspot.com',
    androidClientId: '675039619764-f8rm0le745gdh6ed0jkaks7up3d12bua.apps.googleusercontent.com',
    iosClientId: '675039619764-fr427b1lk1lde9cnv48r13t5haagno8t.apps.googleusercontent.com',
    iosBundleId: 'com.ashu.risepvt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLLFXNIg_qSzwGrmVaEq38bR0ZkAMCQ8M',
    appId: '1:675039619764:ios:0b00cd1f8c28e1d39845e1',
    messagingSenderId: '675039619764',
    projectId: 'riseupgraded',
    storageBucket: 'riseupgraded.appspot.com',
    iosBundleId: 'com.ashu.risepvt',
  );
}